### ISSUE TITLE
XOF and XAF flags are missing

### ISSUE THREAD

**Issue by benz93chung** [cychiang/currency-icons#1]
XOF and XAF flags are missing
https://github.com/cychiang/currency-icons/blob/master/icons/currency/xaf.png
https://github.com/cychiang/currency-icons/blob/master/icons/currency/xof.png

Transferwise's currency-flags has them
https://github.com/transferwise/currency-flags/blob/master/src/flags/xaf.png
https://github.com/transferwise/currency-flags/blob/master/src/flags/xof.png

**Comment by cychiang** [comment]
Hi @benz93chung  thanks for the issue, I have updated the package.
